//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportBulidingDomain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasProfissionais
    {
        public int ID { get; set; }
        public Nullable<int> IDProfissional { get; set; }
        public Nullable<int> IDCondominio { get; set; }
        public Nullable<int> Nota { get; set; }
    }
}
