//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportBulidingDomain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profissionais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profissionais()
        {
            this.ProfissionalEspecialidades = new HashSet<ProfissionalEspecialidades>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public int Idade { get; set; }
        public string Endereco { get; set; }
        public string NumeroRegistro { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public int Status { get; set; }
        public string Sexo { get; set; }
        public int IDPais { get; set; }
        public int IDCidade { get; set; }
        public int IDBairro { get; set; }
        public int IDUF { get; set; }
        public string Comentario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfissionalEspecialidades> ProfissionalEspecialidades { get; set; }
    }
}
