//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportBulidingDomain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ProfissionaisDadosCruzados
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public int Idade { get; set; }
        public string Bairro { get; set; }
        public string Endereco { get; set; }
        public string NumeroRegistro { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Sexo { get; set; }
        public string Comentario { get; set; }
        public int Status { get; set; }
        public string Especialidades { get; set; }
        public string Roles { get; set; }
        public int IDCondominio { get; set; }
        public string NomeCondominio { get; set; }
        public string Celular { get; set; }
        public string NomeResponsavel { get; set; }
        public string CNPJ { get; set; }
    }
}
