//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportBulidingDomain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Condominios
    {
        public int ID { get; set; }
        public string CNPJ { get; set; }
        public string NomeCondominio { get; set; }
        public string Email { get; set; }
        public Nullable<int> IDPais { get; set; }
        public Nullable<int> IDCidade { get; set; }
        public Nullable<int> IDUF { get; set; }
        public string IDBairro { get; set; }
        public string Endereco { get; set; }
        public string Celular { get; set; }
        public string NomeResponsavel { get; set; }
    }
}
