//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportBulidingDomain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfissionalEspecialidades
    {
        public int ID { get; set; }
        public int IDProfissional { get; set; }
        public int IDEspecialidade { get; set; }
        public Nullable<int> ProfissionalID { get; set; }
        public Nullable<int> EspecialidadeID { get; set; }
    
        public virtual Especialidades Especialidades { get; set; }
        public virtual Profissionais Profissionais { get; set; }
    }
}
