//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportBulidingDomain.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportBuildingEntities : DbContext
    {
        public SportBuildingEntities()
            : base("name=SportBuildingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Especialidades> Especialidades { get; set; }
        public virtual DbSet<ProfissionalEspecialidades> ProfissionalEspecialidades { get; set; }
        public virtual DbSet<Bairro> Bairro { get; set; }
        public virtual DbSet<Profissionais> Profissionais { get; set; }
        public virtual DbSet<Cidade> Cidade { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<UF> UF { get; set; }
        public virtual DbSet<NotasProfissionais> NotasProfissionais { get; set; }
        public virtual DbSet<VW_NotasProfissionais> VW_NotasProfissionais { get; set; }
        public virtual DbSet<Condominios> Condominios { get; set; }
        public virtual DbSet<PedidoAula> PedidoAula { get; set; }
        public virtual DbSet<VW_ListaProfissionais> VW_ListaProfissionais { get; set; }
        public virtual DbSet<VW_ProfissionaisDadosCruzados> VW_ProfissionaisDadosCruzados { get; set; }
    }
}
