//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportBulidingDomain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ListaProfissionais
    {
        public int IDProfissional { get; set; }
        public string NomeProfissional { get; set; }
        public int Idade { get; set; }
        public string Sexo { get; set; }
        public string UserName { get; set; }
        public int IDBairro { get; set; }
        public string Bairro { get; set; }
        public int IDEspecialidade { get; set; }
        public string Especialidades { get; set; }
        public Nullable<decimal> MediaNotas { get; set; }
        public Nullable<int> QtdAulas { get; set; }
    }
}
